# Site settings
# in the templates available like {{ site.myvariable }}.
title: Clean portfolio theme for Jekyll powered by Bootstrap 4.
email: fabricarsonho@gmail.com
brand: Fabrica de Sonhos
headline: 1 ano Fabricando seu Sonho!
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 2016 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: fabricarsonho@gmail.com
phone: +55-41-99761-1414

# Tracking
googleAnalitycsID: UA-83933844-1

