# Site settings
# in the templates available like {{ site.myvariable }}.
title: Fabrica de Sonhos.
email: fabricarsonho@gmail.com
brand: Fabrica de Sonhos.
headline: Aqui você sonha e nós realizamos! ❤️
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fabricarsonhos.com" # the base hostname & protocol for your site
copyright: Fabrica de Sonhos

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: fabricarsonho@gmail.com
phone: +55-41-99761-1414

# Tracking
googleAnalitycsID: UA-129610771-1

